# Generated by Django 3.2.5 on 2021-11-15 06:30

import logging

from django.conf import settings
from django.db import migrations

logger = logging.getLogger(__name__)


def create_oauth2_application(apps, schema_editor):
    OAuth2Application = apps.get_model("oauth2_provider.Application")

    application = OAuth2Application.objects.create(
        name=settings.OAUTH2_APPLICATION_NAME,
        redirect_uris=settings.OAUTH2_APPLICATION_REDIRECT_URI,
        client_type="public",
        authorization_grant_type="implicit",
        skip_authorization=True,
    )

    logger.info(
        {
            "event": "Created oauth2 application...",
            "context": {
                "name": settings.OAUTH2_APPLICATION_NAME,
                "redirect_uri": settings.OAUTH2_APPLICATION_REDIRECT_URI,
                "client_id": application.client_id,
            },
        }
    )


def delete_oauth2_application(apps, schema_editor):
    OAuth2Application = apps.get_model("oauth2_provider.Application")

    OAuth2Application.objects.get(name=settings.OAUTH2_APPLICATION_NAME).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
        ("oauth2_provider", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_oauth2_application, delete_oauth2_application)
    ]
